# Site settings
title: Leandro Favarin
url: "https://leandrofavarin.com"
description: Programming, technology, creativity, photography, philosophy, music and more.

# Author
author:
  name: Leandro Favarin
  url: https://leandrofavarin.com
  email: lfavarin@gmail.com
  location: Berlin, Germany

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:title
paginate: 15

collections:
  presentations:
    output: true
    permalink: /:title/

exclude: [vendor]
