# Site settings
title:          Leandro Favarin
description:    "Programming, technology, creativity, photography, philosophy, music and more"
url:            "https://leandrofavarin.com"
# baseurl:        "/"

twitter:
  username: "leandrofavarin"

# Author
author:
  name: Leandro Favarin
  url: https://leandrofavarin.com
  email: lfavarin@gmail.com
  location: Berlin, Germany

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink: /:title
paginate: 15

# Excludes
exclude: [ vendor, Gemfile, Gemfile.lock, tale.gemspec ]
